### ISSUE TITLE
what is broker_path ?

### ISSUE THREAD

**Issue by Barsay** [aegis1980/dash-mqtt#3]
The documentation about this is quite too much self-explanatory.

what is broker_path referring to?

**Comment by aegis1980** [comment]
`broker_path` is [the bit](https://en.wikipedia.org/wiki/URL#:~:text=A-,path,-component%2C%20consisting%20of) after `/` in web URL

e.g. In the example using [emqx public broker](http://tools.emqx.io/) the broker's full RUL is  `ws://broker.emqx.io:8083/mqtt` .  `mqtt` is the path 

There may not be a path on your setup - if so, you'd just omit.
