### ISSUE TITLE
Single DashMqtt instance subscribed to multiple topics.

### ISSUE THREAD

**Issue by taimurrabuske** [aegis1980/dash-mqtt#4]
Hi. Was this a foreseen use case? I tried to use many instances of DashMqtt to process many topics simultaneously, but I started seeing too many errors in the browser console if I use >~10 instances. I suppose the limitation has to do with the WebSockets layer on top of Mqtt. Therefore, I tried a different approach.

I have the following instance:

```
mqtt = dash_mqtt.DashMqtt(
    id="mqtt",
    broker_url=MQTT_SERVER,
    broker_port=MQTT_SERVER_PORT,
    broker_path=MQTT_SERVER_PATH,
    topics=['temp_in', 'rh_in', 'bar_in', 'temp_out', 'rh_out', 'bar_out', 'light', 'light_r', 'light_g', 'light_b',
            'soil_rh_1', 'soil_rh_2', 'soil_rh_3', 'soil_rh_4', 'act_1', 'act_2', 'act_3', 'act_4', 'act_5', 'act_6',
            'act_7', 'act_8'],

    protocol="mqtt",
    options={"protocol": "mqtt", "username": MQTT_USERNAME, "password": MQTT_PASSWORD}
)
```
which subscribes to many topics. 

Then, I have a callback that I create dynamically to process changes in the subscribed topics:

```
def cb_mqtt(incoming):
        # creates an array filled with dash.no_update items.
        ret = [dash.no_update] * len(mqtt.topics)
        # change the value of ret only for the topic of the current message
        if incoming and incoming["topic"] in mqtt.topics:
            i = mqtt.topics.index(incoming['topic'])
            ret[i] =  float(incoming["payload"])
        # returns an array where a single element is a value and the others are dash.no_update.
        return ret

# generate an array of dash outputs, one for each topic/widget (widgets and corresponding topics have the same names).
outputs = [Output(t,'value') for t in mqtt.topics]
# we do not use the more common @app.callback decorator here, in order to process callbacks dynamically.
app.callback(outputs, [Input('mqtt', 'incoming')])(cb_mqtt)
```

Then I set the same name for the topic and the widget I want to update when receiving a message, and I only require one instance of DashMqtt to process many sensors (topics) instead of one instance per topic. Everything works nicely if the delay between messages is > ~50ms. For anything lower than 50 milliseconds, some messages are missed and we see no updates in the widgets.

@aegis1980 is this a proper way to listen to many topics simultaneously?

**Comment by aegis1980** [comment]
Hey, 
Have not used Dash/ MQTT for a long time, so you probably know more about it than me!

Don't think I'd have foreseen multiple DashMqtt instances (to same broker). Don't know why it wouldn't work though. Weird. What error messages did you get in browser?  


No idea why your code for subscribing to multiple topics with a single instance is not working/ throttling either. I wonder if it's this code block:
```
if incoming and incoming["topic"] in mqtt.topics:
    i = mqtt.topics.index(incoming['topic'])
    ret[i] =  float(incoming["payload"]) 
```
`incoming["topic"] in mqtt.topics` and `mqtt.topics.index(incoming['topic'])` are both expensive in terms of [time-complexity](https://yourbasic.org/algorithms/time-complexity-arrays/#:~:text=Expensive%20Python%20list%20operations), but there are so few items in list it shouldn't make that much difference. 

Dunno, not doing much coding these days😢Haven't tried the following - will be interested if it helps 👍

```
# use dict for lookup: O(1) vs O(n)
topics_dict =  { topic : i for topic,i in enumerate(topics) }

def cb_mqtt(incoming):
        # creates an array filled with dash.no_update items.
        ret = [dash.no_update] * len(mqtt.topics)
        # change the value of ret only for the topic of the current message
        if incoming and incoming["topic"] in topics_dict:
            i = topics_dict[incoming['topic']]
            ret[i] = float(incoming["payload"])
        # returns an array where a single element is a value and the others are dash.no_update.
        return ret


# generate an array of dash outputs, one for each topic/widget (widgets and corresponding topics have the same names).
outputs = [Output(t,'value') for t in mqtt.topics]
# we do not use the more common @app.callback decorator here, in order to process callbacks dynamically.
app.callback(outputs, [Input('mqtt', 'incoming')])(cb_mqtt)
```

**Comment by taimurrabuske** [comment]
Hi, thank you for the quick response, and sorry for the delay. 

I don't think it is a performance issue regarding finding repeated elements in a list as the list length is less than 20. 

It could be a limitation of the MQTT.js implementation, maybe. Do you remember how you assigned the QoS in the wrapper?

Thank you.

**Comment by aegis1980** [comment]
Don't think I set a QoS so will be default.
Wil be in `src/lib/components/DashMqtt.react.js` if I did. 
From memory you can set in `options` dict parameter as per MQTT.js docs if you need anything but default.
Good luck.

**Comment by taimurrabuske** [comment]
Thank you! Great job on the package.
